apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo
  namespace: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo

  template:
    metadata:
      labels:
        app: devops-demo

    spec:
      containers:
        - name: devops-demo
          image: makkinakarthik/devops-demo-app:1.0

          ports:
            - containerPort: 5000

          env:
            - name: APP_VERSION
              value: "1.0"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
